package com.partyos.Services;

import com.partyos.Entities.Event;
import com.partyos.Entities.Vendor_Service;
import org.springframework.stereotype.Service;

import java.io.ByteArrayOutputStream;
import java.util.List;
import java.util.Map;

import com.itextpdf.text.*;
import com.itextpdf.text.pdf.*;

@Service
public class PdfService {

    public byte[] generatePdf(Event event,
                             Map<String, List<Vendor_Service>> vendorMap) {

        try {
            ByteArrayOutputStream out = new ByteArrayOutputStream();

            Document document = new Document(PageSize.A4, 40, 40, 50, 50);
            PdfWriter.getInstance(document, out);

            document.open();

            //  FONTS
            Font title = new Font(Font.FontFamily.HELVETICA, 22, Font.BOLD, BaseColor.BLACK);
            Font section = new Font(Font.FontFamily.HELVETICA, 16, Font.BOLD, BaseColor.BLUE);
            Font normal = new Font(Font.FontFamily.HELVETICA, 12);

            //  HEADER
            Paragraph header = new Paragraph("🎉 PartyOS Smart Plan", title);
            header.setAlignment(Element.ALIGN_CENTER);
            header.setSpacingAfter(20);
            document.add(header);

            //  EVENT DETAILS
            document.add(new Paragraph("📋 Event Details", section));

            PdfPTable table = new PdfPTable(2);
            table.setWidthPercentage(100);
            table.setSpacingAfter(20);

            addRow(table, "City", event.getCity());
            addRow(table, "Guests", String.valueOf(event.getGuests()));
            addRow(table, "Budget", "₹ " + event.getBudget());
            addRow(table, "Date", event.getDate());
            addRow(table, "Time", event.getTime());
            addRow(table, "Food", event.getFood());

            document.add(table);

            //  PLAN
            document.add(new Paragraph("✨ Smart Recommendations", section));

            for (String line : event.getPlanSummary().split("\n")) {
                document.add(new Paragraph("• " + line, normal));
            }

            document.add(Chunk.NEWLINE);

            //  VENDORS
            document.add(new Paragraph("🛍 Recommended Vendors", section));

            int totalCost = 0;

            for (String type : vendorMap.keySet()) {

                document.add(new Paragraph("\n" + type + ":", normal));

                List<Vendor_Service> list = vendorMap.get(type);

                int count = 0;

                for (Vendor_Service v : list) {

                    if (count == 2) break; // limit vendors

                    document.add(new Paragraph(
                            v.getBusinessName() +
                            " | ₹" + v.getMinPrice() +
                            " | " + v.getCity(),
                            normal
                    ));

                    totalCost += v.getMinPrice();
                    count++;
                }
            }

            document.add(Chunk.NEWLINE);

            //  COST
            Paragraph cost = new Paragraph(
                    "💰 Estimated Total Cost: ₹ " + totalCost,
                    new Font(Font.FontFamily.HELVETICA, 14, Font.BOLD, BaseColor.RED)
            );

            cost.setSpacingBefore(10);
            document.add(cost);

            //  FOOTER
            Paragraph footer = new Paragraph(
                    "\nGenerated by PartyOS | Plan Smart 🎉",
                    new Font(Font.FontFamily.HELVETICA, 10, Font.ITALIC, BaseColor.GRAY)
            );

            footer.setAlignment(Element.ALIGN_CENTER);
            document.add(footer);

            document.close();

            return out.toByteArray();

        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }

    private void addRow(PdfPTable table, String key, String value) {
        table.addCell(key);
        table.addCell(value);
    }
}